name: KillShotTeams
main: com.github.ZXSkelobrine.KillShot.teams.Central
version: 0.0.1
commands:
  t:
    description: This is the main command for KillShotTeams - it will show the help command.
    usage: /t
permissions:
  killshotteams.*:
    description: This allows access to all of the commands in the plugin.
    children:
      killshotteams.help: true
      killshotteams.create: true
      killshotteams.join: true
      killshotteams.leave: true
      killshotteams.info: true
      killshotteams.chat: true
      killshotteams.hq: true
      killshotteams.disband: true
      killshotteams.sethq: true
      killshotteams.setrally: true
    default: false
  killshotteams.help:
    description: Gives access to the help command.
    default: false
  killshotteams.create:
    description: Gives access to the create command.
    default: false
  killshotteams.join:
    description: Gives access to the join command.
    default: false
  killshotteams.leave:
    description: Gives access to the leave command.
    default: false
  killshotteams.info:
    description: Gives access to the info command.
    default: false
  killshotteams.chat:
    description: Gives access to the chat command.
    default: false
  killshotteams.hq:
    description: Gives access to the hq command.
    default: false
  killshotteams.rally:
    description: Gives access to the rally command.
    default: false
  killshotteams.disband:
    description: Gives access to the disband command.
    default: false
  killshotteams.sethq:
    description: Gives access to the sethq command.
    default: false
  killshotteams.setrally:
    description: Gives access to the setrally command.
    default: false
  killshotteams.password:
    description: Gives access to the password command.
    default: false
  killshotteams.ff:
    description: Gives access to the ff command.
    default: false
  killshotteams.kick:
    description: Gives access to the kick command.
    default: false