name: KillShotTeams
main: com.github.ZXSkelobrine.KillShot.teams.Central;
version: 0.0.1
commands:
  t:
    description: This is the main command for KillShotTeams.
    usage: /t [create] [teamname] [password]